INSERT INTO `config` VALUES (12, 'SITE_NAME', 'Default', 'Site Name', 'The name of this website. This appears in the title of the web browser, and in the footer of the page.', 'string', 2, 'on');
INSERT INTO `config` VALUES (11, 'SCRIPT_FOLDER', '/', 'Script Folder', 'The folder this script resides in, with no trailing slash. Example: if the script is located in www.something.com/foldername/ then this value should be /foldername', 'string', 2, '');
INSERT INTO `config` VALUES (10, 'DOMAIN_NAME', 'example.com', 'Domain Name', 'The domain name of this website. Example: something.com', 'string', 2, '');
INSERT INTO `config` VALUES (9, 'CP_PASSWORD', '', 'cPanel Password', 'Your password for logging into cPanel (used for email forwards)', 'string', 1, '');
INSERT INTO `config` VALUES (8, 'CP_USERNAME', '', 'cPanel User Name', 'Your username to log into cPanel (used for email forwards)', 'string', 1, '');
INSERT INTO `config` VALUES (7, 'CP_HOSTNAME', 'localhost', 'cPanel Host Name', 'The host name for your cPanel server. This is almost always\\"localhost\\" (without quotes)', 'string', 1, '');
INSERT INTO `config` VALUES (13, 'STARTING_PAGE', 'modules/news/', 'Starting Page', 'The location of the first page shown when this site is visited. For example, to show the news page, this should be set to: modules/news/', 'string', 2, 'on');
INSERT INTO `config` VALUES (14, 'MENU_SEPERATOR', '', 'Menu Seperator', 'This will appear between each item in the menu. This is simply used for visual seperation. It can be left blank.', 'string', 2, 'on');
INSERT INTO `config` VALUES (15, 'NEWS_NAME', 'News', 'Name of the News module', 'This is the name of the news module, as it appears in the menus. Examples: News, Blog, What\\''s New', 'string', 3, 'on');
INSERT INTO `config` VALUES (16, 'NEWS_PER_PAGE', '5', 'News Entries per Page', 'This is the number of news entries to be displayed per page.', 'integer', 3, 'on');
INSERT INTO `config` VALUES (17, 'EVENTS_NAME', 'Events', 'Name of the Events Module', 'This is thte name of the Events module, as it appears in the menus. Examples: Events, Shows, Things to do', 'string', 4, 'on');
INSERT INTO `config` VALUES (47, 'STYLESHEET_FOLDER', 'orangefloat', 'Stylesheet Name', 'This is the name of a subfolder within the styles folder that contains the stylesheets to use for the site.', 'string', 2, '');
INSERT INTO `config` VALUES (19, 'MUSIC_NAME', 'Disco', 'Name of the Music Module', 'This is the name of the music page, as it appears in the menus. Examples: Music, Discography, Albums', 'string', 5, 'on');
INSERT INTO `config` VALUES (20, 'MUSIC_PER_PAGE', '3', 'Albums per Page', 'This is the number of albums to display per page.', 'integer', 5, 'on');
INSERT INTO `config` VALUES (21, 'MUSIC_ALBUM_WIDTH', '175', 'Album Cover Width', 'This is the width, in pixels, that an album cover image will be resized to when uploaded. The aspect ratio of the image will be preserved.', 'integer', 5, '');
INSERT INTO `config` VALUES (22, 'GALLERY_NAME', 'Photos', 'Name of the Gallery Module', 'This is the name of the gallery module, as it appears in the menus. Examples: Gallery, Album, Photos', 'string', 6, 'on');
INSERT INTO `config` VALUES (23, 'GALLERY_IMAGE_WIDTH', '385', 'Gallery Image Width', 'The width, in pixels, that all images will be resized to when uploaded into the gallery. The aspect ratio of the images is preserved.', 'integer', 6, '');
INSERT INTO `config` VALUES (24, 'GALLERY_THUMBNAIL_ROWS', '5', 'Thumbnail Rows', 'The number of rows of thumbnails to display on each page of the gallery.', 'integer', 6, '');
INSERT INTO `config` VALUES (25, 'GALLERY_THUMBNAIL_COLS', '3', 'Thumnail Columns', 'The number of columns of thumbnails to display in each page of the gallery.', 'integer', 6, '');
INSERT INTO `config` VALUES (26, 'GALLERY_THUMBNAIL_WIDTH', '55', 'Gallery Thumbnail Width', 'The width, in pixels, of thumbnails displayed in the gallery.', 'integer', 6, '');
INSERT INTO `config` VALUES (27, 'GALLERY_THUMBNAIL_HEIGHT', '33', 'Gallery Thumbnail Height', 'The hight, in pixels, of thumbnails displayed in the gallery.', 'integer', 6, '');
INSERT INTO `config` VALUES (28, 'LINKS_NAME', 'Links', 'Name of the Links Module', 'The name of the links module, as it appears in the menus. Examples: Links, Sites, Places to go', 'string', 7, 'on');
INSERT INTO `config` VALUES (43, 'FOOTER_TEXT', 'Powered by [url=http://www.michiganwebdev.com]mwdcms[/url].', 'Footer text', 'This text appears at the bottom of the page. This is useful for copyright info.', 'string', 2, '');
INSERT INTO `config` VALUES (30, 'PAGES_NAME', 'Pages', 'Name of the Pages Module', 'The name of the pages module, as it appears in the menus.', 'string', 8, '');
INSERT INTO `config` VALUES (31, 'EMAIL_NAME', 'Email', 'Name of the Email Module', 'The name of the email module, as it appears in the menus.', 'string', 9, '');
INSERT INTO `config` VALUES (32, 'EMAIL_FORWARDS', '10', 'Max Email Forwards', 'The maximum number of email forwards allowed to be set in the email module.', 'integer', 9, '');
INSERT INTO `config` VALUES (42, 'USERS_NAME', 'Users', 'Name of the Users Module', 'The name of the users module, as it appears in the menus.', 'string', 11, '');
INSERT INTO `config` VALUES (36, 'SESSION_TIMEOUT', '7200', 'Session Timeout', 'The amount of time before the admin login cookie expires, in seconds. Example: 3600 = 1 hour', 'integer', 2, 'on');
INSERT INTO `config` VALUES (37, 'LINKS_DEFAULT_CATEGORY', 'General', 'Default Links Category', 'When you delete a category of links, all links in that category are moved into the default category. This category cannot be deleted, but it only appears on the links page if it has links within it.', 'string', 7, 'on');
INSERT INTO `config` VALUES (38, 'EVENTS_DATE', 'D, M jS, Y', 'Event Date Format', 'Format of the date as displayed on the events page.  Uses the PHP date format, for info on how to change, see the [url=http://www.php.net/date]PHP Date manual[/url].', 'string', 4, '');
INSERT INTO `config` VALUES (39, 'EVENTS_TIME', 'g:i a', 'Events Time Format', 'Format of the time as displayed on the events page.  Uses the PHP date format, for info on how to change, see the [url=http://www.php.net/date]PHP Date manual[/url].', 'string', 4, '');
INSERT INTO `config` VALUES (40, 'NEWS_DATE', 'D, M jS, Y \\\\a\\\\t g:i a', 'News Date Format', 'Format of the date as displayed on the news page.  Uses the PHP date format, for info on how to change, see the [url=http://www.php.net/date]PHP Date manual[/url].', 'string', 3, '');
INSERT INTO `config` VALUES (41, 'MUSIC_DATE', 'D, M jS, Y', 'Music Date Format', 'Format of the date as displayed on the music page.  Uses the PHP date format, for info on how to change, see the [url=http://www.php.net/date]PHP Date manual[/url].', 'string', 5, '');
INSERT INTO `config` VALUES (44, 'HOST_EMAIL', 'admin@example.com', 'Host E-mail Address', 'The e-mail address of the site host.', 'string', 2, '');
INSERT INTO `config` VALUES (45, 'SITE_EMAIL', 'user@example.com', 'Site E-mail Address', 'The e-mail address of the site.', 'string', 2, 'on');
INSERT INTO `config` VALUES (46, 'CHANGE_PW_NAME', 'Change Password', 'Name of the Change Password menu option', 'This is the name of the change password screen, as it appears in the menus.', 'string', 11, 'on');
INSERT INTO `config_category` VALUES (1, 'cPanel Settings');
INSERT INTO `config_category` VALUES (2, 'General Settings');
INSERT INTO `config_category` VALUES (3, 'News Module');
INSERT INTO `config_category` VALUES (4, 'Events Module');
INSERT INTO `config_category` VALUES (5, 'Music Module');
INSERT INTO `config_category` VALUES (6, 'Gallery Module');
INSERT INTO `config_category` VALUES (7, 'Links Module');
INSERT INTO `config_category` VALUES (8, 'Pages Module');
INSERT INTO `config_category` VALUES (9, 'Email Module');
INSERT INTO `config_category` VALUES (11, 'Users Module');